name: Test Build

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        target:
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
          - linux-arm64-musl
          - linux-amd64-musl
          - windows-arm64
          - android-arm64
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Setup web
        run: bash build.sh dev web
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          FRONTEND_REPO: ${{ vars.FRONTEND_REPO }}

      - name: Build
        uses: OpenListTeam/cgo-actions@v1.2.2
        with:
          targets: ${{ matrix.target }}
          musl-target-format: $os-$musl-$arch
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          out-dir: build
          x-flags: |
            github.com/OpenListTeam/OpenList/internal/v4/conf.BuiltAt=$built_at
            github.com/OpenListTeam/OpenList/internal/v4/conf.GitAuthor=The OpenList Projects Contributors <long2005a3@outlook.com>
            github.com/OpenListTeam/OpenList/internal/v4/conf.GitCommit=$git_commit
            github.com/OpenListTeam/OpenList/internal/v4/conf.Version=$tag
            github.com/OpenListTeam/OpenList/internal/v4/conf.WebVersion=rolling
          output: openlist$ext

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openlist_${{ steps.short-sha.outputs.sha }}_${{ matrix.target }}
          path: build/*